console.log("Hacking your computer...")
console.log("Loading modules...")
console.log("Done")
console.log("Loading database...")
console.log("Done")
console.log("Hacking...")
console.log("This computer is now hacked")
